danger_levels1 = {
    "Vinnytska": 0.0,
    "Volynska": 0.9,
    "Dnipropetrovska": 0.5,
    "Donetska": 1.0,
    "Zhytomyrska": 0.0,
    "Zakarpatska": 0.0,
    "Zaporizka": 0.5,
    "Ivano-Frankivska": 0.0,
    "Kyivska": 0.5,
    "Kirovohradska": 0.1,
    "Luhanska": 1.0,
    "Lvivska": 1.0,
    "Mykolaivska": 0.5,
    "Odeska": 0.5,
    "Poltavska": 0.0,
    "Rivnenska": 0.5,
    "Sumska": 1.0,
    "Ternopilska": 0.7,
    "Kharkivska": 1.0,
    "Khersonska": 0.5,
    "Khmelnytska": 0.1,
    "Cherkaska": 0.5,
    "Chernihivska": 0.25,
    "Chernivetska": 0.65,
    "Kyiv": 0.5,
    "Avtonomna Respublika Krym": 0.5
}

danger_levels2= {
    "Vinnytska": 0.0,
    "Volynska": 0.2,
    "Dnipropetrovska": 0.5,
    "Donetska": 1.0,
    "Zhytomyrska": 0.78,
    "Zakarpatska": 0.55,
    "Zaporizka": 0.5,
    "Ivano-Frankivska": 0.11,
    "Kyivska": 0.5,
    "Kirovohradska": 0.9,
    "Luhanska": 1.0,
    "Lvivska": 1.0,
    "Mykolaivska": 0.86,
    "Odeska": 0.5,
    "Poltavska": 0.2,
    "Rivnenska": 0.78,
    "Sumska": 1.0,
    "Ternopilska": 0.5,
    "Kharkivska": 1.0,
    "Khersonska": 0.65,
    "Khmelnytska": 0.0,
    "Cherkaska": 0.5,
    "Chernihivska": 0.31,
    "Chernivetska": 0.95,
    "Kyiv": 0.5,
    "Avtonomna Respublika Krym": 0.5
}