"""Treck changes

Revision ID: 623e02f160cb
Revises: 
Create Date: 2025-04-05 14:59:50.495667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623e02f160cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alarm')
    # ### end Alembic commands ###
